version: "3"
services:
  ms-iqbal-ravi-betest:
    container_name: ms-iqbal-ravi-betest-container
    image: ms-iqbal-ravi-betest
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - network-iqbal-ravi-betest
  mongo:
    container_name: mongo-container
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - network-iqbal-ravi-betest
  redisdb:
    container_name: redisdb
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - network-iqbal-ravi-betest
networks:
  network-iqbal-ravi-betest:
